# Generated by Django 4.2.11 on 2024-04-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expense_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
