version: "3.8"

services:
  django:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - ./expenses:/code/expenses
      - ./tracker:/code/tracker
    command: python ./manage.py runserver 0:8005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/"]
      interval: 10s
      timeout: 1s
    restart: unless-stopped
